# Generated by Django 6.0.4 on 2026-04-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_cuisine_type_restaurant_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='working_hours',
            field=models.CharField(default='10:00 - 22:00', max_length=100),
        ),
    ]
