# Generated by Django 6.0.3 on 2026-05-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_working_hours'),
        ('restaurants', '0004_workinghours'),
    ]

    operations = [
    ]
