# Generated by Django 6.0.4 on 2026-05-03 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_merge_0004_restaurant_working_hours_0004_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hour_entries', to='restaurants.restaurant'),
        ),
    ]
