# Generated by Django 6.0.3 on 2026-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_add_location_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
