# Generated by Django 6.0.3 on 2026-05-06 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0006_alter_workinghours_restaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_deliveries', models.IntegerField(default=0)),
                ('failed_deliveries', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_delivery_time', models.FloatField(default=0)),
                ('active_drivers', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Aggregation',
                'verbose_name_plural': 'Daily Aggregations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DriverMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deliveries', models.IntegerField(default=0)),
                ('completed_deliveries', models.IntegerField(default=0)),
                ('failed_deliveries', models.IntegerField(default=0)),
                ('avg_delivery_time', models.FloatField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_rating', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Metrics',
                'verbose_name_plural': 'Driver Metrics',
            },
        ),
        migrations.CreateModel(
            name='RestaurantMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_rating', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Metrics',
                'verbose_name_plural': 'Restaurant Metrics',
            },
        ),
    ]
