# Generated by Django 6.0.4 on 2026-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Restaurant Manager'), ('client', 'Client'), ('driver', 'Delivery Driver')], default='client', max_length=20),
        ),
    ]
