# Generated by Django 5.2.13 on 2026-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_date_of_birth_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
