# Generated by Django 6.0.3 on 2026-05-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuitem_price'),
        ('menu', '0005_menuitem_category_menuitem_is_available_and_more'),
    ]

    operations = [
    ]
