# Generated by Django 6.0.4 on 2026-05-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza'), ('pasta', 'Pasta'), ('sandwich', 'Sandwich'), ('salad', 'Salad'), ('soup', 'Soup'), ('appetizer', 'Appetizer'), ('seafood', 'Seafood'), ('grill', 'Grilled Dishes'), ('rice', 'Rice & Risotto'), ('breakfast', 'Breakfast'), ('street_food', 'Street Food'), ('snack', 'Snack'), ('sides', 'Sides & Dips'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('sauce', 'Sauce'), ('traditional', 'Traditional'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
